Data functions for users collection
owaisimran2411/CS546_SemesterProject pull request #1
Opened 2024-04-19 20:56 UTC by JonMike8

2024-04-19 23:04 UTC, mohitcr77 approved these changes
everything looks good, have you tested it?

2024-04-20 05:03 UTC, owaisimran2411 commented
Few suggestions

- Under createUser function, there is an implementation to check if password already exists, no need to check for it, kind of security flaw, we might end up exposing all passwords in our database, second thing, before storing the user data, password needs to be hashed

- some functions are not needed, like updating a username/email address

- can we have one method which will update all variables provided in the function instead of having separate functions for each variable, I think we did something like this in one of our homework lab (don't remember the lab number exactly)

2024-04-20 05:04 UTC, owaisimran2411 requested changes
Few suggestions

- Under createUser function, there is an implementation to check if password already exists, no need to check for it, kind of security flaw, we might end up exposing all passwords in our database, second thing, before storing the user data, password needs to be hashed

- some functions are not needed, like updating a username/email address

- can we have one method which will update all variables provided in the function instead of having separate functions for each variable, I think we did something like this in one of our homework lab (don't remember the lab number exactly)

2024-04-20 15:34 UTC, owaisimran2411 approved these changes

2024-04-20 15:38 UTC, merged